services:
  postgres:
    image: postgres:15-alpine
    container_name: film-postgres
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: nest_project
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U student -d nest_project"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: film-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - postgres
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: film-backend
    image: ghcr.io/katwhite/film-react-nest-backend:latest
    environment:
      DATABASE_DRIVER: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: student
      DATABASE_PASSWORD: student
      DATABASE_NAME: nest_project
      LOG_FORMAT: dev
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  frontend-build:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=/api/afisha
        - VITE_CDN_URL=/content/afisha
    environment:
      - VITE_API_URL=/api/afisha
      - VITE_CDN_URL=/content/afisha
    depends_on:
      - backend
    container_name: film-frontend-builder
    image: ghcr.io/katwhite/film-react-nest-frontend:latest
    volumes:
      - frontend_dist:/dist
    networks:
      - app-network
    

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: film-nginx
    image: ghcr.io/katwhite/film-react-nest-nginx:latest
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend-build
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  frontend_dist:

networks:
  app-network:
    driver: bridge