server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Прокси запросов к API
    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /content/ {
        proxy_pass http://backend:3000/content/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Остальные запросы — отдаём фронтенд
    location / {
        try_files $uri $uri/ /index.html;
    }
}